SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS BOATPOS SALT 'd0099d354b7c5bf3' HASH 'fa7f693e21918e2103db208a4b4ba63dcdbe833683e28852793eec84f917f0f1' ADMIN;       
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;        
CREATE CACHED TABLE PUBLIC.RENTAL_COMMITMENT(
    RENTAL_ID BIGINT NOT NULL,
    COMMITMENT_ID BIGINT NOT NULL
);              
ALTER TABLE PUBLIC.RENTAL_COMMITMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(RENTAL_ID, COMMITMENT_ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RENTAL_COMMITMENT;        
CREATE CACHED TABLE PUBLIC.BOAT(
    ID BIGINT NOT NULL CHECK (ID >= 0),
    VERSION INTEGER NOT NULL CHECK (VERSION >= 0),
    ENABLED BOOLEAN NOT NULL,
    PRIORITY INTEGER NOT NULL CHECK (PRIORITY >= 0),
    COUNT INTEGER NOT NULL CHECK ((COUNT <= 100)
    AND (COUNT >= 0)),
    NAME VARCHAR(50) NOT NULL,
    PICTUREURLLARGE VARCHAR(100) NOT NULL,
    PICTUREURLMEDIUM VARCHAR(100) NOT NULL,
    PICTUREURLSMALL VARCHAR(100) NOT NULL,
    PRICEFORTYFIVEMINUTES DECIMAL(7, 2) NOT NULL CHECK (PRICEFORTYFIVEMINUTES >= 0),
    PRICEONEHOUR DECIMAL(7, 2) NOT NULL CHECK (PRICEONEHOUR >= 0),
    PRICETHIRTYMINUTES DECIMAL(7, 2) NOT NULL CHECK (PRICETHIRTYMINUTES >= 0),
    SHORTNAME VARCHAR(3) NOT NULL
);            
ALTER TABLE PUBLIC.BOAT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BOAT;     
CREATE CACHED TABLE PUBLIC.BOAT_RENTAL(
    BOAT_ID BIGINT NOT NULL,
    RENTALS_ID BIGINT NOT NULL
);         
ALTER TABLE PUBLIC.BOAT_RENTAL ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(BOAT_ID, RENTALS_ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BOAT_RENTAL;              
CREATE CACHED TABLE PUBLIC.COMMITMENT(
    ID BIGINT NOT NULL CHECK (ID >= 0),
    VERSION INTEGER NOT NULL CHECK (VERSION >= 0),
    ENABLED BOOLEAN NOT NULL,
    PRIORITY INTEGER NOT NULL CHECK (PRIORITY >= 0),
    NAME VARCHAR(255) NOT NULL,
    PAPER BOOLEAN
);      
ALTER TABLE PUBLIC.COMMITMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMITMENT;               
CREATE CACHED TABLE PUBLIC.PROMOTION(
    PROMOTIONTYPE VARCHAR(1) NOT NULL,
    ID BIGINT NOT NULL CHECK (ID >= 0),
    VERSION INTEGER NOT NULL CHECK (VERSION >= 0),
    ENABLED BOOLEAN NOT NULL,
    PRIORITY INTEGER NOT NULL CHECK (PRIORITY >= 0),
    FORMULAPRICE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TIMECREDIT INTEGER CHECK (TIMECREDIT >= 0)
);           
ALTER TABLE PUBLIC.PROMOTION ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROMOTION;
CREATE CACHED TABLE PUBLIC.PROMOTION_RENTAL(
    PROMOTION_ID BIGINT NOT NULL,
    RENTALS_ID BIGINT NOT NULL
);               
ALTER TABLE PUBLIC.PROMOTION_RENTAL ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(PROMOTION_ID, RENTALS_ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROMOTION_RENTAL;         
CREATE CACHED TABLE PUBLIC.RENTAL(
    ID BIGINT NOT NULL CHECK (ID >= 0),
    VERSION INTEGER NOT NULL CHECK (VERSION >= 0),
    ARRIVAL DATETIME,
    COUPON BOOLEAN,
    DAY DATE NOT NULL,
    DAYID INTEGER NOT NULL CHECK (DAYID >= 0),
    DELETED BOOLEAN,
    DEPARTURE DATETIME NOT NULL,
    FINISHED BOOLEAN,
    PAYMENTMETHOD VARCHAR(255),
    PRICECALCULATEDAFTER DECIMAL(19, 2) CHECK (PRICECALCULATEDAFTER >= 0),
    PRICECALCULATEDBEFORE DECIMAL(19, 2) CHECK (PRICECALCULATEDBEFORE >= 0),
    PRICEPAIDAFTER DECIMAL(19, 2) CHECK (PRICEPAIDAFTER >= 0),
    PRICEPAIDBEFORE DECIMAL(19, 2) CHECK (PRICEPAIDBEFORE >= 0),
    BOAT_ID BIGINT NOT NULL,
    PROMOTION_ID BIGINT
);      
ALTER TABLE PUBLIC.RENTAL ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RENTAL;   
ALTER TABLE PUBLIC.PROMOTION_RENTAL ADD CONSTRAINT PUBLIC.UK_FGBTJXUDO0BKIONTT5YS0XFM8 UNIQUE(RENTALS_ID);     
ALTER TABLE PUBLIC.BOAT_RENTAL ADD CONSTRAINT PUBLIC.UK_B7BW0M2HPY47IW04W3PI0U150 UNIQUE(RENTALS_ID);          
ALTER TABLE PUBLIC.RENTAL_COMMITMENT ADD CONSTRAINT PUBLIC.FK_5LPYMTNESOQMJQI3XW03CUU87 FOREIGN KEY(RENTAL_ID) REFERENCES PUBLIC.RENTAL(ID) NOCHECK;           
ALTER TABLE PUBLIC.BOAT_RENTAL ADD CONSTRAINT PUBLIC.FK_K22U0LBUKBGQN66HI0TO516N1 FOREIGN KEY(BOAT_ID) REFERENCES PUBLIC.BOAT(ID) NOCHECK;     
ALTER TABLE PUBLIC.RENTAL_COMMITMENT ADD CONSTRAINT PUBLIC.FK_7K6QE75FKH5GD9OUGR54QMEFE FOREIGN KEY(COMMITMENT_ID) REFERENCES PUBLIC.COMMITMENT(ID) NOCHECK;   
ALTER TABLE PUBLIC.PROMOTION_RENTAL ADD CONSTRAINT PUBLIC.FK_44GPGKHDCL30HIX5624MP8GKC FOREIGN KEY(PROMOTION_ID) REFERENCES PUBLIC.PROMOTION(ID) NOCHECK;      
ALTER TABLE PUBLIC.BOAT_RENTAL ADD CONSTRAINT PUBLIC.FK_B7BW0M2HPY47IW04W3PI0U150 FOREIGN KEY(RENTALS_ID) REFERENCES PUBLIC.RENTAL(ID) NOCHECK;
ALTER TABLE PUBLIC.RENTAL ADD CONSTRAINT PUBLIC.FK_6YCSYRLTFKYV93GMEEONH6Q7J FOREIGN KEY(BOAT_ID) REFERENCES PUBLIC.BOAT(ID) NOCHECK;          
ALTER TABLE PUBLIC.PROMOTION_RENTAL ADD CONSTRAINT PUBLIC.FK_FGBTJXUDO0BKIONTT5YS0XFM8 FOREIGN KEY(RENTALS_ID) REFERENCES PUBLIC.RENTAL(ID) NOCHECK;           
ALTER TABLE PUBLIC.RENTAL ADD CONSTRAINT PUBLIC.FK_G2NSO0DCVEDALP443R4YHDO1 FOREIGN KEY(PROMOTION_ID) REFERENCES PUBLIC.PROMOTION(ID) NOCHECK; 
